resilience4j:
  timelimiter:
    configs:
      default:
        cancelRunningFuture: true
        timeoutDuration: 3s
    instances:

      findAll1:
        baseConfig: default
      findAll2:
        baseConfig: default


